<!DOCTYPE html>
<html>
<head>
</head>
<body>
	<h1>List of Emails Generated by a Facility</h1>
	<table>
		<thead>
			<tr>
				<th>Email Subject</th>
				<th>Date</th>
			</tr>
		</thead>
		<tbody>
			<!-- PHP code to fetch and display emails -->
			<?php
				$servername = "localhost";
				$username = "username";
				$password = "password";
				$dbname = "database_name";

				// Create connection
				$conn = mysqli_connect($servername, $username, $password, $dbname);
				// Check connection
				if (!$conn) {
				  die("Connection failed: " . mysqli_connect_error());
				}

				$facility_id = 1; // replace with the ID of the facility to query

				$sql = "SELECT EmailSubject, Date FROM Emails WHERE FacilityID = $facility_id ORDER BY Date ASC";
				$result = mysqli_query($conn, $sql);

				if (mysqli_num_rows($result) > 0) {
					while($row = mysqli_fetch_assoc($result)) {
						echo "<tr>";
						echo "<td>" . $row['EmailSubject'] . "</td>";
						echo "<td>" . $row['Date'] . "</td>";
						echo "</tr>";
					}
				} else {
					echo "<tr><td colspan='2'>No emails found</td></tr>";
				}

				mysqli_close($conn);
			?>
		</tbody>
	</table>
</body>
</html>
